language: python
python:
  - "3.6-dev"
  - "3.7-dev"
before_install:
  - sudo apt-get install -y graphviz
install:
  - pip install graphviz
  - pip install -U -r requirements.txt
  - pip install .
script:
  - pytest -vvv tests
